"""Tests de la logique pure du pont Discord ↔ GitHub.

    python3 -m unittest discover tool/feedback
"""

import os
import unittest
from unittest import mock

import discord_sync as ds

APP_STARTER = {
    "id": "111",
    "author": {"username": "Cono Moto"},
    "content": "",
    "embeds": [
        {
            "title": "💡 Idée : Radars sur la carte",
            "description": "Afficher les radars fixes, avec une alerte vocale.",
            "fields": [
                {"name": "Type", "value": "💡 Idée"},
                {"name": "De la part de", "value": "Julien"},
                {"name": "Appli", "value": "v1.0.0 (build 12, abc1234)"},
                {"name": "Téléphone", "value": "Android 15"},
            ],
            "image": {"url": "https://cdn.discordapp.com/attachments/1/2/capture.jpg"},
        }
    ],
    "reactions": [{"emoji": {"name": "👍"}, "count": 4}, {"emoji": {"name": "🔥"}, "count": 2}],
}


class LogicTest(unittest.TestCase):
    def test_kind(self):
        thread = {"id": "111", "name": "💡 Radars sur la carte", "applied_tags": []}
        self.assertEqual(ds.kind_of(thread, APP_STARTER, {}), "idée")
        self.assertEqual(ds.kind_of({"name": "La carte se fige", "applied_tags": ["9"]}, None, {"9": "Bug"}), "bug")
        self.assertEqual(ds.kind_of({"name": "Salut", "applied_tags": []}, None, {}), "autre")

    def test_votes(self):
        self.assertEqual(ds.votes_of(APP_STARTER), 4)
        self.assertEqual(ds.votes_of({"reactions": None}), 0)
        self.assertEqual(ds.votes_of(None), 0)

    def test_body_from_app_post(self):
        thread = {"id": "111", "name": "💡 Radars sur la carte"}
        body = ds.issue_body(thread, APP_STARTER, "999", 4)
        self.assertIn("Afficher les radars fixes", body)
        self.assertIn("**De :** Julien", body)
        self.assertIn("https://discord.com/channels/999/111", body)
        self.assertIn("**👍 Votes :** 4", body)
        self.assertIn("- Appli : v1.0.0 (build 12, abc1234)", body)
        self.assertIn("![capture](https://cdn.discordapp.com/attachments/1/2/capture.jpg)", body)
        self.assertEqual(ds.thread_id_of({"body": body}), "111")

    def test_body_from_manual_post(self):
        starter = {
            "author": {"username": "seb_moto", "global_name": "Seb"},
            "content": "Ce serait cool d'avoir un mode pluie",
            "embeds": [],
            "attachments": [{"content_type": "image/png", "url": "https://cdn/x.png"}],
        }
        author, text, infos, image = ds.describe_starter(starter)
        self.assertEqual(author, "Seb")
        self.assertEqual(text, "Ce serait cool d'avoir un mode pluie")
        self.assertEqual(infos, [])
        self.assertEqual(image, "https://cdn/x.png")

    def test_title(self):
        self.assertEqual(ds.clean_title("💡 Radars sur la carte"), "Radars sur la carte")
        self.assertEqual(ds.clean_title("   "), "Sans titre")

    def test_votes_update_and_posted_markers(self):
        body = ds.issue_body({"id": "5"}, APP_STARTER, "1", 1)
        body = ds.with_votes(body, 7)
        self.assertIn("**👍 Votes :** 7", body)
        self.assertEqual(ds.posted_ids(body), set())
        body = ds.with_posted(body, {"42"})
        self.assertEqual(ds.posted_ids(body), {"42"})
        body = ds.with_posted(body, {"42", "43"})
        self.assertEqual(ds.posted_ids(body), {"42", "43"})
        self.assertEqual(body.count("discord-posted"), 1)

    def test_discord_text(self):
        comment = (
            "<!-- pour-discord -->\nSalut Julien ! Bonne idée, c'est en cours 🛠️\n\n"
            "---\n_Generated by [Claude Code](https://claude.ai/code)_"
        )
        self.assertEqual(ds.discord_text(comment), "Salut Julien ! Bonne idée, c'est en cours 🛠️")
        self.assertTrue(len(ds.discord_text("x" * 5000)) <= 1901)

    def test_closing(self):
        self.assertIn("C'est fait", ds.closing_message({"state_reason": "completed"}))
        self.assertIn("pas le faire", ds.closing_message({"state_reason": "not_planned"}))

    def test_mentions_neutralized(self):
        self.assertEqual(ds.gh_safe("merci @marc et @everyone"), "merci @\u200bmarc et @\u200beveryone")
        self.assertEqual(ds.gh_safe("mail a @ b"), "mail a @ b")
        body = ds.issue_body({"id": "1"}, {"author": {"username": "x"}, "content": "cc @octocat"}, "9", 0)
        self.assertNotIn("@octocat", body)

    def test_seen_marker(self):
        self.assertEqual(ds.seen_id("pas de marqueur", "111"), "111")
        body = ds.with_seen("texte", "200")
        self.assertEqual(ds.seen_id(body, "111"), "200")
        body = ds.with_seen(body, "300")
        self.assertEqual(ds.seen_id(body, "111"), "300")
        self.assertEqual(body.count("discord-seen"), 1)

    def test_replies_to_copy(self):
        messages = [
            {"id": "130", "author": {"username": "seb"}, "content": "Oui, sur l'autoroute"},
            {"id": "111", "author": {"username": "Cono Moto", "bot": True}, "webhook_id": "5"},
            {"id": "120", "author": {"username": "ConoBot", "bot": True}, "content": "📌 Bien reçu !"},
            {"id": "125", "author": {"username": "julien"}, "content": "Moi aussi", "type": 19},
            {"id": "126", "author": {"username": "julien"}, "content": "", "type": 18},
        ]
        self.assertEqual([m["id"] for m in ds.replies_to_copy(messages, "111")], ["125", "130"])

    def test_reply_comment(self):
        c = ds.reply_comment({
            "id": "130",
            "author": {"username": "seb_moto", "global_name": "Seb"},
            "content": "Ça arrive sur l'A7\nvers Lyon @marc",
            "attachments": [{"content_type": "image/jpeg", "url": "https://cdn/y.jpg"}],
        })
        self.assertIn("**💬 Seb sur Discord :**", c)
        self.assertIn("> Ça arrive sur l'A7\n> vers Lyon @\u200bmarc", c)
        self.assertIn("![capture](https://cdn/y.jpg)", c)
        self.assertIn("<!-- discord-msg:130 -->", c)
        self.assertNotIn(ds.REPLY_MARKER, c)

    def test_relayable_only_from_trusted_authors(self):
        body = ds.REPLY_MARKER + "\nC'est en route !"
        for who in ["OWNER", "MEMBER", "COLLABORATOR"]:
            self.assertTrue(ds.relayable({"body": body, "author_association": who}), who)
        for who in ["CONTRIBUTOR", "FIRST_TIMER", "NONE", None]:
            self.assertFalse(ds.relayable({"body": body, "author_association": who}), who)
        self.assertFalse(ds.relayable({"body": "Sans marqueur", "author_association": "OWNER"}))


WEBHOOK = {"id": "1", "username": "Cono Moto", "bot": True}
APP_MESSAGE = {"id": "610", "type": 0, "webhook_id": "1", "author": WEBHOOK, "content": "",
               "embeds": APP_STARTER["embeds"], "reactions": [{"emoji": {"name": "👍"}, "count": 3}]}
MANUAL_MESSAGE = {"id": "620", "type": 0, "author": {"id": "4", "username": "seb_moto", "global_name": "Seb"},
                  "content": "💡 **Mode pluie** pour la carte <@123>\nAvec des couleurs plus contrastées."}
# Discussion entre potes dans le salon : jamais un ticket.
CHAT_MESSAGE = {"id": "625", "type": 0, "author": {"id": "5", "username": "julien"},
                "content": "Quelqu'un roule ce week-end ? Bug de météo sinon :)"}
PINNED_MESSAGE = {"id": "600", "type": 0, "pinned": True, "webhook_id": "1", "author": WEBHOOK, "content": "",
                  "embeds": [{"title": "📌 Comment ça marche", "description": "Une demande = un message."}]}
BOT_MESSAGE = {"id": "630", "type": 0, "author": {"id": "8", "username": "ConoBot", "bot": True},
               "content": "📌 Bien reçu ! C'est noté (n°1)."}


class TextChannelLogicTest(unittest.TestCase):
    def test_after_cutoff(self):
        self.assertTrue(ds.after_cutoff("620", None))
        self.assertTrue(ds.after_cutoff("620", "610"))
        self.assertFalse(ds.after_cutoff("610", "610"))
        self.assertFalse(ds.after_cutoff("600", "610"))

    def test_channel_id_from_env(self):
        self.assertEqual(ds.channel_id_from({"DISCORD_FORUM_CHANNEL_ID": "42", "DISCORD_CHANNEL_ID": "77"}), "42")
        self.assertEqual(ds.channel_id_from({"DISCORD_FORUM_CHANNEL_ID": " ", "DISCORD_CHANNEL_ID": "77 "}), "77")
        self.assertEqual(ds.channel_id_from({"DISCORD_CHANNEL_ID": "77"}), "77")
        self.assertEqual(ds.channel_id_from({}), "")

    def test_channel_type(self):
        self.assertTrue(ds.is_text_channel({"type": 0}))
        self.assertTrue(ds.is_text_channel({"type": 5}))
        self.assertFalse(ds.is_text_channel({"type": 15}))
        self.assertFalse(ds.is_text_channel({}))

    def test_is_request_message(self):
        self.assertTrue(ds.is_request_message(APP_MESSAGE, "8"))  # webhook de l'appli : une demande
        self.assertTrue(ds.is_request_message(MANUAL_MESSAGE, "8"))
        self.assertTrue(ds.is_request_message(dict(MANUAL_MESSAGE, type=19), "8"))  # réponse à un message
        self.assertTrue(ds.is_request_message(MANUAL_MESSAGE, None))
        self.assertTrue(ds.is_request_message(dict(MANUAL_MESSAGE, content="🐞 La carte se fige"), "8"))
        self.assertTrue(ds.is_request_message(dict(MANUAL_MESSAGE, content="Bug : la carte se fige"), "8"))
        # La discussion du salon n'est pas une demande, réponse ou non, même avec une image.
        self.assertFalse(ds.is_request_message(CHAT_MESSAGE, "8"))
        self.assertFalse(ds.is_request_message(dict(CHAT_MESSAGE, type=19), "8"))
        self.assertFalse(ds.is_request_message(
            {"id": "1", "author": {"id": "4"}, "content": "", "attachments": [{"url": "https://cdn/x.png"}]}, "8"))
        self.assertFalse(ds.is_request_message(PINNED_MESSAGE, "8"))
        # Annonce postée par le webhook sans la fiche de l'appli : pas une demande.
        announce = {"id": "640", "type": 0, "webhook_id": "1", "author": WEBHOOK, "content": "Salut ! Tes idées sont faites."}
        self.assertFalse(ds.is_request_message(announce, "8"))
        self.assertTrue(ds.is_app_post(APP_MESSAGE))
        self.assertFalse(ds.is_app_post(announce))
        self.assertFalse(ds.is_request_message(BOT_MESSAGE, "8"))
        self.assertFalse(ds.is_request_message(dict(BOT_MESSAGE, author={"id": "8"}), "8"))
        self.assertFalse(ds.is_request_message(dict(BOT_MESSAGE, author={"id": "9", "bot": True}), "8"))
        self.assertFalse(ds.is_request_message(dict(MANUAL_MESSAGE, type=6), "8"))  # « a épinglé un message »
        self.assertFalse(ds.is_request_message(dict(MANUAL_MESSAGE, type=18), "8"))  # « a créé un fil »
        self.assertFalse(ds.is_request_message(dict(MANUAL_MESSAGE, content="  "), "8"))
        self.assertFalse(ds.is_request_message(None, "8"))

    def test_is_explicit_request(self):
        for text in ("💡 Mode pluie", "  🐞 La carte se fige", "Idée : mode pluie", "idee: mode pluie",
                     "BUG : ça plante", "Idée\u00a0: mode pluie", "💡**Mode pluie**"):
            self.assertTrue(ds.is_explicit_request(text), text)
        for text in ("Grave, +1", "Une idée pour samedi ?", "Bug de météo sinon :)", "Mode pluie 💡",
                     "Bugs : aucun", "", None):
            self.assertFalse(ds.is_explicit_request(text), text)

    def test_needs_thread(self):
        self.assertTrue(ds.needs_thread(APP_MESSAGE, "8"))
        self.assertFalse(ds.needs_thread(dict(APP_MESSAGE, thread={"id": "610"}), "8"))
        self.assertFalse(ds.needs_thread(dict(APP_MESSAGE, flags=32), "8"))
        self.assertFalse(ds.needs_thread(PINNED_MESSAGE, "8"))

    def test_thread_title(self):
        self.assertEqual(ds.thread_title(APP_MESSAGE), "Radars sur la carte")
        bug = {"content": "", "embeds": [{"title": "🐞 Bug : La carte se fige", "description": "Plus rien."}]}
        self.assertEqual(ds.thread_title(bug), "La carte se fige")
        self.assertEqual(ds.thread_title(MANUAL_MESSAGE), "💡 Mode pluie pour la carte")
        # Message écrit à la main avec un aperçu de lien : c'est le texte qui compte
        link = {"content": "\n> Regardez ça <:moto:42> https://exemple.fr", "embeds": [{"title": "Exemple"}]}
        self.assertEqual(ds.thread_title(link), "Regardez ça :moto: https://exemple.fr")
        long = ds.thread_title({"content": "Ce serait vraiment super " * 10})
        self.assertLessEqual(len(long), 100)
        self.assertTrue(long.endswith("super…"))
        long = ds.thread_title({"content": "Ce serait vraiment génial " * 10})
        self.assertLessEqual(len(long), 100)
        self.assertTrue(long.endswith("vraiment…"))  # « gé… » évité
        only_image = {"author": {"username": "seb_moto", "global_name": "Seb"}, "content": "",
                      "attachments": [{"url": "https://cdn/x.png"}]}
        self.assertEqual(ds.thread_title(only_image), "Demande de Seb")

    def test_crash_report_from_app(self):
        # Rapport de plantage envoyé tout seul par l'appli (lib/core/crash_reporter.dart) :
        # une demande de type bug comme une autre, sans pseudo.
        crash = {
            "id": "700", "type": 0, "webhook_id": "1", "author": WEBHOOK, "content": "",
            "embeds": [{
                "title": "💥 Plantage : StateError dans RideController.stop",
                "description": "```\nBad state: No element\n```\n**Écran :** RideScreen\n\n"
                               "**Pile d'appels**\n```\nRideController.stop (package:cono_moto/x.dart:1:1)\n```",
                "fields": [
                    {"name": "Type", "value": "🐞 Bug"},
                    {"name": "Appli", "value": "v1.0.0 (build 12)"},
                    {"name": "Téléphone", "value": "Android 15"},
                ],
            }],
        }
        self.assertTrue(ds.is_app_post(crash))
        self.assertTrue(ds.is_request_message(crash, "8"))
        thread = {"id": "700", "name": "💥 Plantage : StateError dans RideController.stop", "applied_tags": []}
        self.assertEqual(ds.kind_of(thread, crash, {}), "bug")
        self.assertEqual(ds.thread_title(crash), "💥 Plantage : StateError dans RideController.stop")
        body = ds.issue_body(thread, crash, "999", 0)
        self.assertIn("RideController.stop (package:cono_moto/x.dart:1:1)", body)
        self.assertIn("**De :** Cono Moto", body)
        self.assertIn("- Appli : v1.0.0 (build 12)", body)

    def test_clean_title_without_kind_prefix(self):
        self.assertEqual(ds.clean_title("🐞 Bug : La carte se fige"), "La carte se fige")
        self.assertEqual(ds.clean_title("Idée: mode pluie"), "mode pluie")
        self.assertEqual(ds.clean_title("Bugs et idées en vrac"), "Bugs et idées en vrac")


class FakeApi:
    """Discord + GitHub en mémoire, branchés à la place de Http."""

    def __init__(self):
        self.threads = {"500": {"id": "500", "name": "🐞 La carte se fige", "parent_id": "42", "applied_tags": []}}
        self.messages = {
            "500": [
                {"id": "500", "author": {"username": "Cono Moto", "bot": True}, "webhook_id": "1",
                 "content": "", "embeds": [{"description": "Plus rien ne bouge après 10 min.",
                                            "fields": [{"name": "Type", "value": "🐞 Bug"},
                                                       {"name": "De la part de", "value": "Julien"}]}]},
            ]
        }
        self.issues: list[dict] = []
        self.comments: dict[int, list[dict]] = {}
        self.discord_posts: list[tuple[str, str]] = []
        self.next_id = 900

    def new_id(self):
        self.next_id += 1
        return str(self.next_id)

    def discord(self, method, path, body):
        if path == "/channels/42":
            return {"guild_id": "7", "available_tags": []}
        if path == "/guilds/7/threads/active":
            return {"threads": list(self.threads.values())}
        if path.startswith("/channels/42/threads/archived"):
            return {"threads": []}
        tid = path.split("/")[2]
        if method == "GET" and "?after=" in path:
            after = int(path.split("after=")[1].split("&")[0])
            return [m for m in self.messages[tid] if int(m["id"]) > after][::-1]
        if method == "GET":
            return self.messages[tid][0]
        if method == "POST":
            self.discord_posts.append((tid, body["content"]))
            self.messages[tid].append({"id": self.new_id(), "author": {"username": "ConoBot", "bot": True},
                                       "content": body["content"]})
            return {}
        raise AssertionError(path)

    def github(self, method, path, body):
        if path.endswith("/labels?per_page=100"):
            return []
        if path.endswith("/labels"):
            return {}
        if method == "GET" and "/issues?labels=feedback" in path:
            return self.issues
        if method == "POST" and path.endswith("/issues"):
            issue = {"number": len(self.issues) + 1, "state": "open", **body}
            self.issues.append(issue)
            self.comments[issue["number"]] = []
            return issue
        number = int(path.split("/issues/")[1].split("/")[0].split("?")[0])
        issue = self.issues[number - 1]
        if "/comments" in path and method == "GET":
            return self.comments[number]
        if "/comments" in path and method == "POST":
            self.comments[number].append({"id": int(self.new_id()), **body})
            return {}
        if method == "PATCH":
            issue.update(body)
            return issue
        raise AssertionError(path)

    def http(self, base, headers):
        route = self.discord if base == ds.DISCORD_API else self.github

        class _Http:
            def call(self, method, path, body=None):
                return route(method, path, body)

        return _Http()


class MainTest(unittest.TestCase):
    ENV = {"DISCORD_BOT_TOKEN": "t", "DISCORD_FORUM_CHANNEL_ID": "42", "GITHUB_TOKEN": "g",
           "GITHUB_REPOSITORY": "moi/cono-moto"}

    def run_sync(self, api):
        with mock.patch.dict(os.environ, self.ENV), mock.patch.object(ds, "Http", api.http), \
                mock.patch("builtins.print"):
            return ds.main()

    def test_full_conversation(self):
        api = FakeApi()
        # 1. Nouveau fil → ticket + « bien reçu »
        self.assertEqual(self.run_sync(api), 0)
        self.assertEqual(len(api.issues), 1)
        issue = api.issues[0]
        self.assertEqual(issue["title"], "[Bug] La carte se fige")
        self.assertEqual(issue["labels"], ["feedback", "bug"])
        self.assertIn("Bien reçu", api.discord_posts[0][1])
        self.assertEqual(api.comments[1], [])

        # 2. Claude pose une question sur GitHub → repostée dans le fil
        api.comments[1].append({"id": 1, "body": ds.REPLY_MARKER + "\nSalut Julien ! Android ou iPhone ?",
                                "author_association": "OWNER"})
        # Un inconnu qui imite le marqueur (dépôt public) n'est pas reposté.
        api.comments[1].append({"id": 2, "body": ds.REPLY_MARKER + "\nPub pour mon site",
                                "author_association": "NONE"})
        self.run_sync(api)
        self.assertEqual(api.discord_posts[-1][1], "Salut Julien ! Android ou iPhone ?")
        self.assertFalse(any("Pub" in p for _, p in api.discord_posts))

        # 3. Julien répond dans Discord → recopié sur GitHub, une seule fois
        api.messages["500"].append({"id": api.new_id(), "author": {"username": "julien"}, "content": "iPhone 13"})
        self.run_sync(api)
        self.run_sync(api)
        copied = [c for c in api.comments[1] if "discord-msg" in c["body"]]
        self.assertEqual(len(copied), 1)
        self.assertIn("> iPhone 13", copied[0]["body"])
        self.assertEqual(sum("Android ou iPhone" in p for _, p in api.discord_posts), 1)

        # 4. Ticket fermé → annonce une seule fois
        issue["state"] = "closed"
        issue["state_reason"] = "completed"
        self.run_sync(api)
        self.run_sync(api)
        self.assertEqual(sum("C'est fait" in p for _, p in api.discord_posts), 1)

    def test_without_secrets_does_nothing(self):
        with mock.patch.dict(os.environ, {"DISCORD_BOT_TOKEN": "", "DISCORD_FORUM_CHANNEL_ID": ""}), \
                mock.patch("builtins.print"):
            self.assertEqual(ds.main(), 0)


class FakeTextApi(FakeApi):
    """Salon texte « 77 » : une demande = un message du salon, le bot (id 8)
    ouvre un fil dessous, et le fil porte l'id du message."""

    def __init__(self):
        super().__init__()
        system = {"id": "601", "type": 6, "author": {"id": "3", "username": "marc"}, "content": ""}
        self.channel = [PINNED_MESSAGE, system, APP_MESSAGE, MANUAL_MESSAGE, CHAT_MESSAGE, BOT_MESSAGE]
        self.threads = {"5000": {"id": "5000", "name": "Fil d'un autre salon", "parent_id": "99"}}
        self.messages = {}  # messages des fils
        self.opened: list[tuple[str, str]] = []

    def discord(self, method, path, body):
        if path == "/channels/77":
            return {"id": "77", "type": 0, "guild_id": "7"}
        if path == "/users/@me":
            return {"id": "8", "username": "ConoBot", "bot": True}
        if path == "/guilds/7/threads/active":
            return {"threads": list(self.threads.values())}
        if path.startswith("/channels/77/threads/archived"):
            return {"threads": []}
        if path == "/channels/77/messages?limit=100":
            return [dict(m, thread=self.threads[m["id"]]) if m["id"] in self.threads else m
                    for m in reversed(self.channel)]
        if method == "POST" and path.startswith("/channels/77/messages/") and path.endswith("/threads"):
            mid = path.split("/")[4]
            if mid in self.threads:
                raise RuntimeError("400 : ce message a déjà un fil")
            self.threads[mid] = {"id": mid, "name": body["name"], "parent_id": "77", "type": 11}
            self.messages[mid] = [{"id": self.new_id(), "type": 21, "author": {"username": "seb_moto"},
                                   "content": "", "message_reference": {"message_id": mid}}]
            self.opened.append((mid, body["name"]))
            return self.threads[mid]
        if method == "GET" and path.startswith("/channels/77/messages/"):
            found = [m for m in self.channel if m["id"] == path.split("/")[4]]
            if not found:
                raise RuntimeError("404 : message introuvable")
            return found[0]
        tid = path.split("/")[2]
        if tid not in self.messages:
            raise AssertionError(f"{method} {path}")
        if method == "GET" and "?after=" in path:
            after = int(path.split("after=")[1].split("&")[0])
            return [m for m in self.messages[tid] if int(m["id"]) > after][::-1]
        if method == "POST" and path == f"/channels/{tid}/messages":
            self.discord_posts.append((tid, body["content"]))
            self.messages[tid].append({"id": self.new_id(), "author": {"id": "8", "username": "ConoBot", "bot": True},
                                       "content": body["content"]})
            return {}
        # Dans un salon texte, le 1er message n'est pas dans le fil.
        raise AssertionError(f"{method} {path}")


class TextChannelTest(unittest.TestCase):
    ENV = {"DISCORD_BOT_TOKEN": "t", "DISCORD_FORUM_CHANNEL_ID": "", "DISCORD_CHANNEL_ID": "77",
           "GITHUB_TOKEN": "g", "GITHUB_REPOSITORY": "moi/cono-moto"}

    def run_sync(self, api):
        with mock.patch.dict(os.environ, self.ENV), mock.patch.object(ds, "Http", api.http), \
                mock.patch("builtins.print"):
            return ds.main()

    def test_messages_before_cutoff_ignored(self):
        api = FakeTextApi()
        env = {**self.ENV, "DISCORD_SINCE_ID": "615"}
        with mock.patch.dict(os.environ, env), mock.patch.object(ds, "Http", api.http), mock.patch("builtins.print"):
            self.assertEqual(ds.main(), 0)
        self.assertEqual([m for m, _ in api.opened], ["620"])
        self.assertEqual(len(api.issues), 1)

    def test_text_channel(self):
        api = FakeTextApi()
        # 1. Un fil sous la demande de l'appli et sous le 💡 de Seb, rien d'autre
        self.assertEqual(self.run_sync(api), 0)
        self.assertEqual(api.opened, [("610", "Radars sur la carte"), ("620", "💡 Mode pluie pour la carte")])
        self.assertEqual([i["title"] for i in api.issues],
                         ["[Idée] Radars sur la carte", "[Idée] Mode pluie pour la carte"])
        self.assertEqual(api.issues[0]["labels"], ["feedback", "idée"])
        self.assertEqual(api.issues[1]["labels"], ["feedback", "idée"])
        body = api.issues[0]["body"]
        self.assertIn("Afficher les radars fixes", body)
        self.assertIn("**De :** Julien", body)
        self.assertIn("**👍 Votes :** 3", body)
        self.assertIn("https://discord.com/channels/7/610", body)
        self.assertEqual(ds.thread_id_of(api.issues[1]), "620")
        self.assertIn("**De :** Seb", api.issues[1]["body"])
        self.assertIn("Avec des couleurs plus contrastées.", api.issues[1]["body"])
        # « Bien reçu » dans chaque fil (jamais dans le salon), épinglé, discussion et bot ignorés
        self.assertEqual([tid for tid, _ in api.discord_posts], ["610", "620"])
        self.assertTrue(all("Bien reçu" in p for _, p in api.discord_posts))
        self.assertNotIn("600", api.threads)
        self.assertNotIn("625", api.threads)
        self.assertNotIn("630", api.threads)

        # 2. Deuxième passage : rien n'est recréé
        self.assertEqual(self.run_sync(api), 0)
        self.assertEqual(len(api.opened), 2)
        self.assertEqual(len(api.issues), 2)
        self.assertEqual(len(api.discord_posts), 2)

        # 3. Les réponses des potes se lisent dans le fil, pas dans le salon
        api.messages["620"].append({"id": api.new_id(), "author": {"username": "julien"}, "content": "Grave, +1"})
        api.channel.append({"id": api.new_id(), "type": 0, "author": {"id": "4", "username": "seb_moto"},
                            "content": "Et un mode nuit ?"})
        self.assertEqual(self.run_sync(api), 0)
        copied = [c["body"] for c in api.comments[2] if "discord-msg" in c["body"]]
        self.assertEqual(len(copied), 1)
        self.assertIn("> Grave, +1", copied[0])
        self.assertEqual(api.comments[1], [])
        # … la discussion du salon reste de la discussion …
        self.assertEqual(len(api.opened), 2)
        self.assertEqual(len(api.issues), 2)

        # 4. … et un message qui commence par 🐞 est une nouvelle demande
        api.channel.append({"id": api.new_id(), "type": 0, "author": {"id": "4", "username": "seb_moto"},
                            "content": "🐞 La carte se fige au démarrage"})
        self.assertEqual(self.run_sync(api), 0)
        self.assertEqual(api.opened[-1][1], "🐞 La carte se fige au démarrage")
        self.assertEqual(api.issues[-1]["title"], "[Bug] La carte se fige au démarrage")
        self.assertEqual(api.issues[-1]["labels"], ["feedback", "bug"])

    def test_masked_content_fails_loudly(self):
        # Sans « Message Content Intent », Discord vide les messages des autres :
        # la demande de l'appli n'a plus sa fiche, le pont doit le signaler.
        api = FakeTextApi()
        api.channel = [dict(m, content="", embeds=[], attachments=[]) if m["id"] == "610" else m
                       for m in api.channel]
        printed = []
        with mock.patch.dict(os.environ, self.ENV), mock.patch.object(ds, "Http", api.http), \
                mock.patch("builtins.print", side_effect=lambda *a, **k: printed.append(" ".join(map(str, a)))):
            self.assertEqual(ds.main(), 1)
        self.assertTrue(any("Message Content Intent" in line for line in printed))
        self.assertEqual([m for m, _ in api.opened], ["620"])

    def test_looks_masked(self):
        self.assertTrue(ds.looks_masked({"id": "1", "type": 0, "webhook_id": "1", "author": WEBHOOK, "content": "",
                                         "embeds": [], "attachments": []}, "8"))
        self.assertFalse(ds.looks_masked(APP_MESSAGE, "8"))
        self.assertFalse(ds.looks_masked(MANUAL_MESSAGE, "8"))
        self.assertFalse(ds.looks_masked({"id": "2", "type": 0, "author": {"id": "8"}, "content": ""}, "8"))
        self.assertFalse(ds.looks_masked({"id": "3", "type": 0, "author": {"id": "4"}, "content": "",
                                          "sticker_items": [{"id": "9"}]}, "8"))
        self.assertFalse(ds.looks_masked({"id": "4", "type": 7, "author": {"id": "4"}, "content": ""}, "8"))
        self.assertFalse(ds.looks_masked(None, "8"))

    def test_thread_on_pinned_message_is_not_a_ticket(self):
        api = FakeTextApi()
        # Quelqu'un a ouvert un fil à la main sous le « Comment ça marche » épinglé
        api.threads["600"] = {"id": "600", "name": "Comment ça marche", "parent_id": "77", "type": 11}
        api.messages["600"] = []
        self.assertEqual(self.run_sync(api), 0)
        self.assertEqual(len(api.issues), 2)
        self.assertNotIn("600", [ds.thread_id_of(i) for i in api.issues])
        self.assertNotIn("600", [tid for tid, _ in api.discord_posts])


if __name__ == "__main__":
    unittest.main()
