"""Tests de la logique pure du pont Discord ↔ GitHub.

    python3 -m unittest discover tool/feedback
"""

import os
import unittest
from unittest import mock

import discord_sync as ds

APP_STARTER = {
    "id": "111",
    "author": {"username": "Cono Moto"},
    "content": "",
    "embeds": [
        {
            "title": "💡 Idée : Radars sur la carte",
            "description": "Afficher les radars fixes, avec une alerte vocale.",
            "fields": [
                {"name": "Type", "value": "💡 Idée"},
                {"name": "De la part de", "value": "Julien"},
                {"name": "Appli", "value": "v1.0.0 (build 12, abc1234)"},
                {"name": "Téléphone", "value": "Android 15"},
            ],
            "image": {"url": "https://cdn.discordapp.com/attachments/1/2/capture.jpg"},
        }
    ],
    "reactions": [{"emoji": {"name": "👍"}, "count": 4}, {"emoji": {"name": "🔥"}, "count": 2}],
}


class LogicTest(unittest.TestCase):
    def test_kind(self):
        thread = {"id": "111", "name": "💡 Radars sur la carte", "applied_tags": []}
        self.assertEqual(ds.kind_of(thread, APP_STARTER, {}), "idée")
        self.assertEqual(ds.kind_of({"name": "La carte se fige", "applied_tags": ["9"]}, None, {"9": "Bug"}), "bug")
        self.assertEqual(ds.kind_of({"name": "Salut", "applied_tags": []}, None, {}), "autre")

    def test_votes(self):
        self.assertEqual(ds.votes_of(APP_STARTER), 4)
        self.assertEqual(ds.votes_of({"reactions": None}), 0)
        self.assertEqual(ds.votes_of(None), 0)

    def test_body_from_app_post(self):
        thread = {"id": "111", "name": "💡 Radars sur la carte"}
        body = ds.issue_body(thread, APP_STARTER, "999", 4)
        self.assertIn("Afficher les radars fixes", body)
        self.assertIn("**De :** Julien", body)
        self.assertIn("https://discord.com/channels/999/111", body)
        self.assertIn("**👍 Votes :** 4", body)
        self.assertIn("- Appli : v1.0.0 (build 12, abc1234)", body)
        self.assertIn("![capture](https://cdn.discordapp.com/attachments/1/2/capture.jpg)", body)
        self.assertEqual(ds.thread_id_of({"body": body}), "111")

    def test_body_from_manual_post(self):
        starter = {
            "author": {"username": "seb_moto", "global_name": "Seb"},
            "content": "Ce serait cool d'avoir un mode pluie",
            "embeds": [],
            "attachments": [{"content_type": "image/png", "url": "https://cdn/x.png"}],
        }
        author, text, infos, image = ds.describe_starter(starter)
        self.assertEqual(author, "Seb")
        self.assertEqual(text, "Ce serait cool d'avoir un mode pluie")
        self.assertEqual(infos, [])
        self.assertEqual(image, "https://cdn/x.png")

    def test_title(self):
        self.assertEqual(ds.clean_title("💡 Radars sur la carte"), "Radars sur la carte")
        self.assertEqual(ds.clean_title("   "), "Sans titre")

    def test_votes_update_and_posted_markers(self):
        body = ds.issue_body({"id": "5"}, APP_STARTER, "1", 1)
        body = ds.with_votes(body, 7)
        self.assertIn("**👍 Votes :** 7", body)
        self.assertEqual(ds.posted_ids(body), set())
        body = ds.with_posted(body, {"42"})
        self.assertEqual(ds.posted_ids(body), {"42"})
        body = ds.with_posted(body, {"42", "43"})
        self.assertEqual(ds.posted_ids(body), {"42", "43"})
        self.assertEqual(body.count("discord-posted"), 1)

    def test_discord_text(self):
        comment = (
            "<!-- pour-discord -->\nSalut Julien ! Bonne idée, c'est en cours 🛠️\n\n"
            "---\n_Generated by [Claude Code](https://claude.ai/code)_"
        )
        self.assertEqual(ds.discord_text(comment), "Salut Julien ! Bonne idée, c'est en cours 🛠️")
        self.assertTrue(len(ds.discord_text("x" * 5000)) <= 1901)

    def test_closing(self):
        self.assertIn("C'est fait", ds.closing_message({"state_reason": "completed"}))
        self.assertIn("pas le faire", ds.closing_message({"state_reason": "not_planned"}))

    def test_mentions_neutralized(self):
        self.assertEqual(ds.gh_safe("merci @marc et @everyone"), "merci @\u200bmarc et @\u200beveryone")
        self.assertEqual(ds.gh_safe("mail a @ b"), "mail a @ b")
        body = ds.issue_body({"id": "1"}, {"author": {"username": "x"}, "content": "cc @octocat"}, "9", 0)
        self.assertNotIn("@octocat", body)

    def test_seen_marker(self):
        self.assertEqual(ds.seen_id("pas de marqueur", "111"), "111")
        body = ds.with_seen("texte", "200")
        self.assertEqual(ds.seen_id(body, "111"), "200")
        body = ds.with_seen(body, "300")
        self.assertEqual(ds.seen_id(body, "111"), "300")
        self.assertEqual(body.count("discord-seen"), 1)

    def test_replies_to_copy(self):
        messages = [
            {"id": "130", "author": {"username": "seb"}, "content": "Oui, sur l'autoroute"},
            {"id": "111", "author": {"username": "Cono Moto", "bot": True}, "webhook_id": "5"},
            {"id": "120", "author": {"username": "ConoBot", "bot": True}, "content": "📌 Bien reçu !"},
            {"id": "125", "author": {"username": "julien"}, "content": "Moi aussi", "type": 19},
            {"id": "126", "author": {"username": "julien"}, "content": "", "type": 18},
        ]
        self.assertEqual([m["id"] for m in ds.replies_to_copy(messages, "111")], ["125", "130"])

    def test_reply_comment(self):
        c = ds.reply_comment({
            "id": "130",
            "author": {"username": "seb_moto", "global_name": "Seb"},
            "content": "Ça arrive sur l'A7\nvers Lyon @marc",
            "attachments": [{"content_type": "image/jpeg", "url": "https://cdn/y.jpg"}],
        })
        self.assertIn("**💬 Seb sur Discord :**", c)
        self.assertIn("> Ça arrive sur l'A7\n> vers Lyon @\u200bmarc", c)
        self.assertIn("![capture](https://cdn/y.jpg)", c)
        self.assertIn("<!-- discord-msg:130 -->", c)
        self.assertNotIn(ds.REPLY_MARKER, c)


class FakeApi:
    """Discord + GitHub en mémoire, branchés à la place de Http."""

    def __init__(self):
        self.threads = {"500": {"id": "500", "name": "🐞 La carte se fige", "parent_id": "42", "applied_tags": []}}
        self.messages = {
            "500": [
                {"id": "500", "author": {"username": "Cono Moto", "bot": True}, "webhook_id": "1",
                 "content": "", "embeds": [{"description": "Plus rien ne bouge après 10 min.",
                                            "fields": [{"name": "Type", "value": "🐞 Bug"},
                                                       {"name": "De la part de", "value": "Julien"}]}]},
            ]
        }
        self.issues: list[dict] = []
        self.comments: dict[int, list[dict]] = {}
        self.discord_posts: list[tuple[str, str]] = []
        self.next_id = 900

    def new_id(self):
        self.next_id += 1
        return str(self.next_id)

    def discord(self, method, path, body):
        if path == "/channels/42":
            return {"guild_id": "7", "available_tags": []}
        if path == "/guilds/7/threads/active":
            return {"threads": list(self.threads.values())}
        if path.startswith("/channels/42/threads/archived"):
            return {"threads": []}
        tid = path.split("/")[2]
        if method == "GET" and "?after=" in path:
            after = int(path.split("after=")[1].split("&")[0])
            return [m for m in self.messages[tid] if int(m["id"]) > after][::-1]
        if method == "GET":
            return self.messages[tid][0]
        if method == "POST":
            self.discord_posts.append((tid, body["content"]))
            self.messages[tid].append({"id": self.new_id(), "author": {"username": "ConoBot", "bot": True},
                                       "content": body["content"]})
            return {}
        raise AssertionError(path)

    def github(self, method, path, body):
        if path.endswith("/labels?per_page=100"):
            return []
        if path.endswith("/labels"):
            return {}
        if method == "GET" and "/issues?labels=feedback" in path:
            return self.issues
        if method == "POST" and path.endswith("/issues"):
            issue = {"number": len(self.issues) + 1, "state": "open", **body}
            self.issues.append(issue)
            self.comments[issue["number"]] = []
            return issue
        number = int(path.split("/issues/")[1].split("/")[0].split("?")[0])
        issue = self.issues[number - 1]
        if "/comments" in path and method == "GET":
            return self.comments[number]
        if "/comments" in path and method == "POST":
            self.comments[number].append({"id": int(self.new_id()), **body})
            return {}
        if method == "PATCH":
            issue.update(body)
            return issue
        raise AssertionError(path)

    def http(self, base, headers):
        route = self.discord if base == ds.DISCORD_API else self.github

        class _Http:
            def call(self, method, path, body=None):
                return route(method, path, body)

        return _Http()


class MainTest(unittest.TestCase):
    ENV = {"DISCORD_BOT_TOKEN": "t", "DISCORD_FORUM_CHANNEL_ID": "42", "GITHUB_TOKEN": "g",
           "GITHUB_REPOSITORY": "moi/cono-moto"}

    def run_sync(self, api):
        with mock.patch.dict(os.environ, self.ENV), mock.patch.object(ds, "Http", api.http), \
                mock.patch("builtins.print"):
            return ds.main()

    def test_full_conversation(self):
        api = FakeApi()
        # 1. Nouveau fil → ticket + « bien reçu »
        self.assertEqual(self.run_sync(api), 0)
        self.assertEqual(len(api.issues), 1)
        issue = api.issues[0]
        self.assertEqual(issue["title"], "[Bug] La carte se fige")
        self.assertEqual(issue["labels"], ["feedback", "bug"])
        self.assertIn("Bien reçu", api.discord_posts[0][1])
        self.assertEqual(api.comments[1], [])

        # 2. Claude pose une question sur GitHub → repostée dans le fil
        api.comments[1].append({"id": 1, "body": ds.REPLY_MARKER + "\nSalut Julien ! Android ou iPhone ?"})
        self.run_sync(api)
        self.assertEqual(api.discord_posts[-1][1], "Salut Julien ! Android ou iPhone ?")

        # 3. Julien répond dans Discord → recopié sur GitHub, une seule fois
        api.messages["500"].append({"id": api.new_id(), "author": {"username": "julien"}, "content": "iPhone 13"})
        self.run_sync(api)
        self.run_sync(api)
        copied = [c for c in api.comments[1] if "discord-msg" in c["body"]]
        self.assertEqual(len(copied), 1)
        self.assertIn("> iPhone 13", copied[0]["body"])
        self.assertEqual(sum("Android ou iPhone" in p for _, p in api.discord_posts), 1)

        # 4. Ticket fermé → annonce une seule fois
        issue["state"] = "closed"
        issue["state_reason"] = "completed"
        self.run_sync(api)
        self.run_sync(api)
        self.assertEqual(sum("C'est fait" in p for _, p in api.discord_posts), 1)

    def test_without_secrets_does_nothing(self):
        with mock.patch.dict(os.environ, {"DISCORD_BOT_TOKEN": "", "DISCORD_FORUM_CHANNEL_ID": ""}), \
                mock.patch("builtins.print"):
            self.assertEqual(ds.main(), 0)


if __name__ == "__main__":
    unittest.main()
