"""Tests de la logique pure du pont Discord ↔ GitHub.

    python3 -m unittest discover tool/feedback
"""

import unittest

import discord_sync as ds

APP_STARTER = {
    "id": "111",
    "author": {"username": "Cono Moto"},
    "content": "",
    "embeds": [
        {
            "title": "💡 Idée : Radars sur la carte",
            "description": "Afficher les radars fixes, avec une alerte vocale.",
            "fields": [
                {"name": "Type", "value": "💡 Idée"},
                {"name": "De la part de", "value": "Julien"},
                {"name": "Appli", "value": "v1.0.0 (build 12, abc1234)"},
                {"name": "Téléphone", "value": "Android 15"},
            ],
            "image": {"url": "https://cdn.discordapp.com/attachments/1/2/capture.jpg"},
        }
    ],
    "reactions": [{"emoji": {"name": "👍"}, "count": 4}, {"emoji": {"name": "🔥"}, "count": 2}],
}


class LogicTest(unittest.TestCase):
    def test_kind(self):
        thread = {"id": "111", "name": "💡 Radars sur la carte", "applied_tags": []}
        self.assertEqual(ds.kind_of(thread, APP_STARTER, {}), "idée")
        self.assertEqual(ds.kind_of({"name": "La carte se fige", "applied_tags": ["9"]}, None, {"9": "Bug"}), "bug")
        self.assertEqual(ds.kind_of({"name": "Salut", "applied_tags": []}, None, {}), "autre")

    def test_votes(self):
        self.assertEqual(ds.votes_of(APP_STARTER), 4)
        self.assertEqual(ds.votes_of({"reactions": None}), 0)
        self.assertEqual(ds.votes_of(None), 0)

    def test_body_from_app_post(self):
        thread = {"id": "111", "name": "💡 Radars sur la carte"}
        body = ds.issue_body(thread, APP_STARTER, "999", 4)
        self.assertIn("Afficher les radars fixes", body)
        self.assertIn("**De :** Julien", body)
        self.assertIn("https://discord.com/channels/999/111", body)
        self.assertIn("**👍 Votes :** 4", body)
        self.assertIn("- Appli : v1.0.0 (build 12, abc1234)", body)
        self.assertIn("![capture](https://cdn.discordapp.com/attachments/1/2/capture.jpg)", body)
        self.assertEqual(ds.thread_id_of({"body": body}), "111")

    def test_body_from_manual_post(self):
        starter = {
            "author": {"username": "seb_moto", "global_name": "Seb"},
            "content": "Ce serait cool d'avoir un mode pluie",
            "embeds": [],
            "attachments": [{"content_type": "image/png", "url": "https://cdn/x.png"}],
        }
        author, text, infos, image = ds.describe_starter(starter)
        self.assertEqual(author, "Seb")
        self.assertEqual(text, "Ce serait cool d'avoir un mode pluie")
        self.assertEqual(infos, [])
        self.assertEqual(image, "https://cdn/x.png")

    def test_title(self):
        self.assertEqual(ds.clean_title("💡 Radars sur la carte"), "Radars sur la carte")
        self.assertEqual(ds.clean_title("   "), "Sans titre")

    def test_votes_update_and_posted_markers(self):
        body = ds.issue_body({"id": "5"}, APP_STARTER, "1", 1)
        body = ds.with_votes(body, 7)
        self.assertIn("**👍 Votes :** 7", body)
        self.assertEqual(ds.posted_ids(body), set())
        body = ds.with_posted(body, {"42"})
        self.assertEqual(ds.posted_ids(body), {"42"})
        body = ds.with_posted(body, {"42", "43"})
        self.assertEqual(ds.posted_ids(body), {"42", "43"})
        self.assertEqual(body.count("discord-posted"), 1)

    def test_discord_text(self):
        comment = (
            "<!-- pour-discord -->\nSalut Julien ! Bonne idée, c'est en cours 🛠️\n\n"
            "---\n_Generated by [Claude Code](https://claude.ai/code)_"
        )
        self.assertEqual(ds.discord_text(comment), "Salut Julien ! Bonne idée, c'est en cours 🛠️")
        self.assertTrue(len(ds.discord_text("x" * 5000)) <= 1901)

    def test_closing(self):
        self.assertIn("C'est fait", ds.closing_message({"state_reason": "completed"}))
        self.assertIn("pas le faire", ds.closing_message({"state_reason": "not_planned"}))


if __name__ == "__main__":
    unittest.main()
